// question bank (generated by questionBank.js)
const qBank = questionBank

// question and score tracker
const userData = {
	question: 0,
	posScore: 0,
	negScore: 0,
	totalQuestions: 10
}

// Sets the field used to display questions and prompts
function setLegend (legendText) {	
	$('.answerForm').append(`<legend>${legendText}</legend>`)
}

// Renders the start screen for users' initial landing
function handleFirstVisit() {
	// clear out anything that might already be in quizbox
	$('.answerForm').empty()
	setLegend("Ready to test your knowledge about the strange world you live in?")	
	$('.answerForm').append('<button class=\"startButton js-nextButton\">Let\'s go!</button>')
}

// Handles actions when next/start are clicked
function handleNextButton() {	
	$('.quizBox').on('click', '.js-nextButton', event => {		
		// checks to see if user has seen all questions
		if (userData.question >= userData.totalQuestions) {
		handleFinal();
		} else {
		userData.question += 1;
		handleNewQuestion();
		};
	})	
}

// listener for answer buttons
function handleAnswerClicked() {		
	$('.answerForm').on('click','.answer', e=> {		
		let selectedAnswer = $(e.target).text()		
		let qNum = userData.question;
		let question = qBank[qNum-1];
		// sets correct to 1 or 0 depending on whether the answer is correct
		let correct = question.isCorrect(selectedAnswer);		
		handleFeedback(correct);
	});
}

// creates the footer with question number and current score
function createFooter() {	
	$('.answerForm').append(`
		<footer>				
			<div class="pageCount">
				<p>Question ${userData.question} of ${userData.totalQuestions}</p>	
			</div>		
			<div class="score">
				<span class="posScore">+${userData.posScore}</span>/<span class="negScore">-${userData.negScore}</span>
			</div>
		</footer>
		`);						
}

function cleanup() {
	$('.answerForm').empty();
	$('footer').remove();
	$('.feedbackForm').remove();
	$('.nextButton').remove();
}

// Renders new question, answers, score, and page count
function handleNewQuestion() {
	// To the right of that, he sees his current score: +0/-0, with the plusses and minuses in large playful fonts, colored green and red respectively. 
	// Hovering his mouse over a button, Clarence notices it changes color
	
	// clear previous items
	cleanup()
	let qNum = userData.question;
	let question = qBank[qNum-1];
	let answers = question.generateAnswers()	
	// grabs the question at qNum index and sets the question text to qText
	setLegend(question.qText);

	// creates buttons for each answer
	for (let i=0;i<answers.length;i++) {
		$('.answerForm').append(`<button class=\"answer\">${answers[i]}</button>`)
	};

	// add footer
	createFooter();
}

// Listens for user input and generates feedback
function handleFeedback(correct) {	 	
	let qNum = userData.question;
	let question = qBank[qNum-1];
	let answers = $('.answer');
	const contextFeedback = {}
	// set appropriate feedback and adjust score
	if (correct) {
		contextFeedback.primary = 'Correct!';
		contextFeedback.secondary = "";
		userData.posScore += 1; 
	} else {
		contextFeedback.primary = 'Incorrect!';
		contextFeedback.secondary = ""
		userData.negScore += 1;
	}

	// redraw footer to display updated score
	$('footer').remove()
	createFooter()

	// add feedback box
	$('.quizBox').append(`
		<div class="feedbackForm">					
			<p><span class="primaryFeedback">${contextFeedback.primary} </span><span class="secondaryFeedback">${contextFeedback.secondary}</span></p>										
		</div>
		`)

	// give it the appropriate class
	if (correct) {
		$('feedbackForm').addClass("correct")
	} else {
		$('feedbackForm').addClass("incorrect")
	}

	// animate answers hinging out
	for (let i=0;i<Object.keys(answers).length;i++) {
		let ansBut = answers[i];		
		let answer = $(ansBut).text();		
		if (question.isCorrect(answer)) {			
		} else {
			$(ansBut).addClass("animated hinge")
		};
	}

	// add next button
	$('.quizBox').append(`<div class="nextButton js-nextButton"><button>next ></button></div>`)
}

// Renders a summary page with user score and start over button
function handleFinal() {	
	console.log("handleFinal ran")
	cleanup()

	// checks if we need to pluralize 'question'
	let positiveScore = userData.posScore + ' question';
	let negativeScore = userData.negScore + ' question';
	if (userData.posScore != 1) {
		positiveScore += 's'
	};
	if (userData.negscore !=1) {
		negativeScore += 's'
	}	
	$('.answerForm').append(`
		<legend>OK, let's see how you did:</legend>
		<h3>You got ${positiveScore} correct,</h3>
		<h3>and ${negativeScore} incorrect</h3>
		<button class="resetButton">Start over?</button>
		`)

	// handle startover
	$('.resetButton').click(e => {
		userData.posScore = 0;
		userData.negscore = 0;
		userData.question = 0;
		handleFirstVisit();
	})

}

function handleQuiz() {
	$('.answerForm').submit(e => {
		e.preventDefault();
	})
	handleNextButton();
	handleAnswerClicked();	
	handleFirstVisit();	
}

$(handleQuiz())
